services:
  mongo:
    image: mongo:5
    restart: always
    networks:
      - internal
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-frontend
    image: tulip-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - api
    networks:
      - internal
    environment:
      API_SERVER_ENDPOINT: http://api:5000/

  api:
    build:
      context: services/api
      dockerfile: Dockerfile-api
    image: tulip-api:latest
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      TULIP_TRAFFIC_DIR: ${TRAFFIC_DIR_DOCKER}
      FLAG_REGEX: ${FLAG_REGEX}
      TICK_START: ${TICK_START}
      TICK_LENGTH: ${TICK_LENGTH}
      VM_IP: ${VM_IP}

  flagids:
    restart: on-failure
    build:
      context: services/flagids
    image: tulip-flagids:latest
    depends_on:
      - mongo
    networks:
      - internal
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      TICK_START: ${TICK_START}
      TICK_LENGTH: ${TICK_LENGTH}
      FLAGID_SCRAPE: ${FLAGID_SCRAPE}
      TEAM_ID: ${TEAM_ID}
      FLAGID_ENDPOINT: ${FLAGID_ENDPOINT}

  assembler:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-assembler
    image: tulip-assembler:latest
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro
    command: "./assembler -dir ${TRAFFIC_DIR_DOCKER}"
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      FLAG_REGEX: ${FLAG_REGEX}
      TICK_LENGTH: ${TICK_LENGTH}
      FLAGID_SCAN: ${FLAGID_SCAN}
      FLAG_LIFETIME: ${FLAG_LIFETIME}
    extra_hosts:
      - "host.docker.internal:host-gateway"


  enricher:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-enricher
    image: tulip-enricher:latest
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro
      - ./suricata/logs:/var/log/suricata:ro
    command: "./enricher -eve /var/log/suricata/eve.json"
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      FLAG_REGEX: ${FLAG_REGEX}
      FLAGID_SCAN: ${FLAGID_SCAN}
      FLAG_LIFETIME: ${FLAG_LIFETIME}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pcap-manager:
    image: alpine:latest
    restart: unless-stopped
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}
    environment:
      TRAFFIC_DIR_DOCKER: ${TRAFFIC_DIR_DOCKER}
    command: >
      sh -c "
        mkdir -p ${TRAFFIC_DIR_DOCKER}/captures_old &&
        while true; do
          find ${TRAFFIC_DIR_DOCKER} -maxdepth 1 -type f -name '*.pcap*' -mmin +30 -exec mv {} ${TRAFFIC_DIR_DOCKER}/captures_old/ \;
          sleep 60
        done
      "
networks:
  internal:
